### Spring ###
spring:

  ### Application ###
  application:
    name: auth-server

  ### Config ###
  config:
    import: configserver:http://localhost:9999

  ### Cloud config ###
  cloud:
    config:
      failFast: true
      profile: default